CREATE TABLE recipe (
    recipe_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_key VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL,
    shorts_reference VARCHAR(2048) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_recipe_dataset_key UNIQUE (dataset_key)
);

CREATE TABLE recipe_ingredient (
    recipe_ingredient_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id BIGINT NOT NULL,
    ingredient_id BIGINT,
    display_name VARCHAR(255) NOT NULL,
    raw_text TEXT NOT NULL,
    amount VARCHAR(255),
    unit VARCHAR(255),
    display_order INTEGER NOT NULL,
    CONSTRAINT fk_recipe_ingredient_recipe
        FOREIGN KEY (recipe_id) REFERENCES recipe (recipe_id) ON DELETE CASCADE,
    CONSTRAINT fk_recipe_ingredient_ingredient
        FOREIGN KEY (ingredient_id) REFERENCES ingredient (ingredient_id),
    CONSTRAINT uq_recipe_ingredient_recipe_display_order
        UNIQUE (recipe_id, display_order),
    CONSTRAINT uq_recipe_ingredient_recipe_ingredient
        UNIQUE (recipe_id, ingredient_id)
);

CREATE TABLE recipe_step (
    recipe_step_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id BIGINT NOT NULL,
    step_order INTEGER NOT NULL,
    content TEXT NOT NULL,
    CONSTRAINT fk_recipe_step_recipe
        FOREIGN KEY (recipe_id) REFERENCES recipe (recipe_id) ON DELETE CASCADE,
    CONSTRAINT uq_recipe_step_recipe_step_order
        UNIQUE (recipe_id, step_order)
);

CREATE INDEX idx_recipe_ingredient_recipe_id
    ON recipe_ingredient (recipe_id);
CREATE INDEX idx_recipe_ingredient_ingredient_id
    ON recipe_ingredient (ingredient_id);
CREATE INDEX idx_recipe_step_recipe_id
    ON recipe_step (recipe_id);
