name: app
description: Whipup Flutter application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.3.0
  kakao_flutter_sdk_user: ^2.0.1
  api_client:
    path: packages/api_client

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/onboarding/
    - assets/ingredient/
    - assets/recipe/
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
