String? ingredientAssetPathFor(String canonicalName) {
  return _ingredientAssetPaths[canonicalName];
}

const _ingredientAssetPaths = <String, String>{
  '계란': 'assets/ingredient/egg.png',
  '마늘': 'assets/ingredient/garlic.png',
  '김치': 'assets/ingredient/kimchi.png',
  '대파': 'assets/ingredient/green_onion.png',
  '양파': 'assets/ingredient/onion.png',
  '팽이버섯': 'assets/ingredient/enoki_mushroom.png',
  '양배추': 'assets/ingredient/cabbage.png',
  '김': 'assets/ingredient/seaweed.png',
  '고추': 'assets/ingredient/chili_pepper.png',
  '삼겹살': 'assets/ingredient/pork_belly.png',
  '우삼겹': 'assets/ingredient/beef_belly.png',
  '베이컨': 'assets/ingredient/bacon.png',
  '소시지': 'assets/ingredient/sausage.png',
  '만두': 'assets/ingredient/dumpling.png',
  '치즈': 'assets/ingredient/cheese.png',
  '밥': 'assets/ingredient/rice.png',
  '우유': 'assets/ingredient/milk.png',
  '간장': 'assets/ingredient/fallback_soy_bottle.png',
  '굴소스': 'assets/ingredient/fallback_soy_bottle.png',
  '참치액': 'assets/ingredient/fallback_soy_bottle.png',
  '참기름': 'assets/ingredient/fallback_oil_bottle.png',
  '식용유': 'assets/ingredient/fallback_oil_bottle.png',
  '올리브오일': 'assets/ingredient/fallback_oil_bottle.png',
  '케찹': 'assets/ingredient/fallback_sauce_bottle.png',
  '식초': 'assets/ingredient/fallback_clear_bottle.png',
  '맛술': 'assets/ingredient/fallback_clear_bottle.png',
  '고추장': 'assets/ingredient/fallback_tub.png',
  '버터': 'assets/ingredient/fallback_tub.png',
  '알룰로스': 'assets/ingredient/fallback_tub.png',
  '물엿': 'assets/ingredient/fallback_tub.png',
  '와사비': 'assets/ingredient/fallback_tub.png',
  '고춧가루': 'assets/ingredient/fallback_powder.png',
  '설탕': 'assets/ingredient/fallback_powder.png',
  '소금': 'assets/ingredient/fallback_powder.png',
  '후추': 'assets/ingredient/fallback_powder.png',
  '레드페퍼': 'assets/ingredient/fallback_powder.png',
  '깨': 'assets/ingredient/fallback_powder.png',
  '코인육수': 'assets/ingredient/fallback_bag.png',
  '치킨스톡': 'assets/ingredient/fallback_bag.png',
  '파스타면': 'assets/ingredient/fallback_bag.png',
  '물': 'assets/ingredient/fallback_bowl.png',
};
